version: "3"
services:
    php:
        image: nanoninja/php-fpm
        container_name: nuvem_php
        restart: always
        user: www-data
        working_dir: /var/www/html
        volumes:
            - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html"
        ports:
            - "9000:9000"